export enum ReservationStatus {
  NEW = 'NEW',
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}

export enum RoomType {
  DELUXE_SUITE = 'DELUXE_SUITE',
  EXECUTIVE_SUITE = 'EXECUTIVE_SUITE',
  ROYAL_SUITE = 'ROYAL_SUITE',
  STANDARD_DOUBLE = 'STANDARD_DOUBLE',
  FAMILY_SUITE = 'FAMILY_SUITE',
}
